---
- name: enable eigrp ipv6 rid
  ios_config:
    defaults: yes
    parents: ipv6 router eigrp {{ routing.as }}
    lines:
      - router-id {{ routing.rid }}
- name: enable eigrp ipv6 passive-interface
  ios_config:
    defaults: yes
    parents: ipv6 router eigrp {{ routing.as }}
    lines:
      - passive-interface {{ item }}
  loop: "{{ routing.passive }}"
  when: routing.passive is defined
- name: enable eigrp ipv6 on interfaces
  ios_config:
    defaults: yes
    parents: interface {{ item.id }}
    lines:
      - ipv6 eigrp {{ routing.as }}
  loop: "{{ routing.eigrp6 }}"
