---
- name: configure ipv4 addresses
  ios_l3_interfaces:
    config:
      - name: "{{ item.id }}"
        ipv4:
        - address: "{{ item.ipv4_address | ipaddr('host/prefix') }}"
  loop: "{{ interfaces }}"
  when:
    - item.id is defined
    - item.trunk.vlans is undefined
    - item.ipv4_address is defined
    - item.ipv4_address | ipv4
  failed_when:
    - not item.ipv4_address | ipaddr('host/prefix')
- name: configure ipv4 addresses on a trunk
  ios_config:
    defaults: no
    parents: interface {{ item.id }}
    lines:
      - ip address {{ item.ipv4_address | ipaddr('address') }} {{ item.ipv4_address | ipaddr('netmask') }}
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.id is defined
    - item.trunk.vlans is defined
    - item.ipv4_address is defined
    - item.ipv4_address | ipv4
  failed_when:
    - not item.ipv4_address | ipaddr('host/prefix')
- name: configure ipv4 addresses as dhcp client
  ios_l3_interfaces:
    config:
      - name: "{{ item.id }}"
        ipv4:
        - address: "dhcp"
  loop: "{{ interfaces }}"
  when:
    - item.id is defined
    - item.ipv4_address is defined
    - item.ipv4_address == 'dhcp'
