---
- name: configure ipv4 addresses
  ios_l3_interfaces:
    config:
      - name: "{{ item.id }}"
        ipv4:
        - address: "{{ item.ipv4_address | ipaddr('address') }} {{ item.ipv4_address | ipaddr('netmask') }}"
  loop: "{{ interfaces }}"
  when:
    - item.id is defined
    - item.ipv4_address is defined
    - item.ipv4_address | ipv4
failed_when:
  - not item | ipaddr('host/prefix')
- name: configure ipv4 addresses as dhcp client
  ios_l3_interfaces:
    config:
      - name: "{{ item.id }}"
        ipv4:
        - address: "dhcp"
  loop: "{{ interfaces }}"
  when:
    - item.id is defined
    - item.ipv4_address is defined
    - item.ipv4_address == 'dhcp'
