---
- import_tasks: enable_rip.yml
  when: ansible_network_os == 'ios'
  tags:
    - rip
    - ipv4_dynamic_routing
- import_tasks: static_to_rip.yml
  when:
    - ansible_network_os == 'ios'
    - nat is defined
  tags:
    - rip
    - static_to_rip
    - ipv4_dynamic_routing
