gns3_url: "http://172.16.253.1"
gns3_lab_user: root
gns3_lab_pass: testtest
project_name: "tripod_switchblock_lab"
gns3_nodes_spec:
  - name: "controller"
    template: "controller"
    x: -500
    y: 300
  - name: "R1"
    template: "Cisco IOSv 15.7(3)M3"
    x: 0
    y: -200
  - name: "R2"
    template: "Cisco IOSv 15.7(3)M3"
    x: -100
    y: -100
  - name: "R3"
    template: "Cisco IOSv 15.7(3)M3"
    x: 100
    y: -100
  - name: "S1"
    template: "Ethernet switch"
    x: -100
    y: -185
  - name: "S2"
    template: "Ethernet switch"
    x: -200
    y: -85
  - name: "S3"
    template: "Ethernet switch"
    x: 200
    y: -85
  - name: "nat0"
    template: "NAT"
    x: 100
    y: -200
  - name: "DS1"
    template: "Cisco IOSvL2 15.2.1"
    x: -100
    y: 45
  - name: "DS2"
    template: "Cisco IOSvL2 15.2.1"
    x: 100
    y: 45
  - name: "AS1"
    template: "Cisco IOSvL2 15.2.1"
    x: -100
    y: 200
  - name: "AS2"
    template: "Cisco IOSvL2 15.2.1"
    x: 100
    y: 200
  - name: "PC1"
    template: "VPCS"
    x: -200
    y: -200
  - name: "PC2"
    template: "VPCS"
    x: -300
    y: -100
  - name: "PC3"
    template: "VPCS"
    x: 300
    y: -100
  - name: "PC110"
    template: "VPCS"
    x: -200
    y: 350
  - name: "PC120"
    template: "VPCS"
    x: -150
    y: 350
  - name: "PC130"
    template: "VPCS"
    x: -100
    y: 350
  - name: "PC140"
    template: "VPCS"
    x: -50
    y: 350
  - name: "PC210"
    template: "VPCS"
    x: 50
    y: 350
  - name: "PC220"
    template: "VPCS"
    x: 100
    y: 350
  - name: "PC230"
    template: "VPCS"
    x: 150
    y: 350
  - name: "PC240"
    template: "VPCS"
    x: 200
    y: 350
  - name: "ctrl0"
    template: "Ethernet switch"
    x: -500
    y: 200
  - name: "ctrl1"
    template: "Ethernet switch"
    x: -500
    y: 100
  - name: "nat1"
    template: "NAT"
    x: -700
    y: 300
gns3_links_spec:
  - ["R1", "Gi0/0", "S1", "Ethernet0"]
  - ["S1", "Ethernet1", "PC1", "Ethernet0"]
  - ["R2", "Gi0/0", "S2", "Ethernet0"]
  - ["S2", "Ethernet1", "PC2", "Ethernet0"]
  - ["R3", "Gi0/0", "S3", "Ethernet0"]
  - ["S3", "Ethernet1", "PC3", "Ethernet0"]
  - ["R1", "Gi0/2", "R2", "Gi0/1"]
  - ["R1", "Gi0/3", "R3", "Gi0/1"]
  - ["R2", "Gi0/3", "R3", "Gi0/2"]
  - ["R1", "Gi0/1", "nat0", "nat0"]
  - ["DS1", "Gi2/0", "R2", "Gi0/2"]
  - ["DS1", "Gi3/0", "R2", "Gi0/4"]
  - ["DS1", "Gi2/1", "R3", "Gi0/5"]
  - ["DS1", "Gi3/1", "R3", "Gi0/6"]
  - ["DS2", "Gi2/0", "R3", "Gi0/3"]
  - ["DS2", "Gi3/0", "R3", "Gi0/4"]
  - ["DS2", "Gi2/1", "R2", "Gi0/5"]
  - ["DS2", "Gi3/1", "R2", "Gi0/6"]
  - ["DS1", "Gi0/0", "AS1", "Gi0/0"]
  - ["DS1", "Gi1/0", "AS1", "Gi1/0"]
  - ["DS1", "Gi0/1", "AS2", "Gi0/1"]
  - ["DS1", "Gi1/1", "AS2", "Gi1/1"]
  - ["DS2", "Gi0/0", "AS2", "Gi0/0"]
  - ["DS2", "Gi1/0", "AS2", "Gi1/0"]
  - ["DS2", "Gi0/1", "AS1", "Gi0/1"]
  - ["DS2", "Gi1/1", "AS1", "Gi1/1"]
  - ["DS1", "Gi0/2", "DS2", "Gi0/2"]
  - ["DS1", "Gi1/2", "DS2", "Gi1/2"]
  - ["AS1", "Gi2/0", "PC110", "Ethernet0"]
  - ["AS1", "Gi2/1", "PC120", "Ethernet0"]
  - ["AS1", "Gi2/2", "PC130", "Ethernet0"]
  - ["AS1", "Gi2/3", "PC140", "Ethernet0"]
  - ["AS2", "Gi2/0", "PC210", "Ethernet0"]
  - ["AS2", "Gi2/1", "PC220", "Ethernet0"]
  - ["AS2", "Gi2/2", "PC230", "Ethernet0"]
  - ["AS2", "Gi2/3", "PC240", "Ethernet0"]
  - ["R1", "Gi0/7", "ctrl1", "Ethernet1"]
  - ["R2", "Gi0/7", "ctrl1", "Ethernet2"]
  - ["R3", "Gi0/7", "ctrl1", "Ethernet3"]
  - ["ctrl0", "Ethernet7", "ctrl1", "Ethernet0"]
  - ["DS1", "Gi3/3", "ctrl0", "Ethernet1"]
  - ["DS2", "Gi3/3", "ctrl0", "Ethernet2"]
  - ["AS1", "Gi3/3", "ctrl0", "Ethernet3"]
  - ["AS2", "Gi3/3", "ctrl0", "Ethernet4"]
  - ["ctrl0", "Ethernet0", "controller", "Ethernet0"]
  - ["controller", "Ethernet1", "nat1", "nat0"]
