gns3_url: "http://172.16.253.1"
gns3_lab_user: root
gns3_lab_pass: testtest
project_name: "router_on_a_stick_lab"
gns3_nodes_spec:
  - name: "controller"
    template: "controller"
    x: -200
    y: -265
  - name: "R1"
    template: "Cisco IOSv 15.7(3)M3"
    x: 0
    y: -200
  - name: "SW0"
    template: "Cisco IOSvL2 15.2.1"
    x: 0
    y: -100
  - name: "SW1"
    template: "Cisco IOSvL2 15.2.1"
    x: 0
    y: 0
  - name: "nat0"
    template: "NAT"
    x: 100
    y: -200
  - name: "PC1-VLAN10"
    template: "VPCS"
    x: -100
    y: -100
  - name: "PC1-VLAN20"
    template: "VPCS"
    x: 100
    y: -100
  - name: "PC2-VLAN10"
    template: "VPCS"
    x: -100
    y: 0
  - name: "PC2-VLAN20"
    template: "VPCS"
    x: 100
    y: 0
  - name: "ctrl0"
    template: "Ethernet switch"
    x: -100
    y: -250
  - name: "nat1"
    template: "NAT"
    x: -400
    y: -265
gns3_links_spec:
  - ["R1", "Gi0/1", "nat0", "nat0"]
  - ["R1", "Gi0/0", "SW0", "Gi0/2"]
  - ["SW0", "Gi0/1", "SW1", "Gi0/1"]
  - ["SW0", "Gi1/0", "PC1-VLAN10", "Ethernet0"]
  - ["SW0", "Gi2/0", "PC1-VLAN20", "Ethernet0"]
  - ["SW1", "Gi1/0", "PC2-VLAN10", "Ethernet0"]
  - ["SW1", "Gi2/0", "PC2-VLAN20", "Ethernet0"]
  - ["R1", "Gi0/7", "ctrl0", "Ethernet1"]
  - ["SW0", "Gi3/3", "ctrl0", "Ethernet2"]
  - ["SW1", "Gi3/3", "ctrl0", "Ethernet3"]
  - ["ctrl0", "Ethernet0", "controller", "Ethernet0"]
  - ["controller", "Ethernet1", "nat1", "nat0"]
