---
# Based on https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#playbooks-filters-ipaddr
- name: Using ipaddr filter and check on ip address variables
  hosts: localhost
  gather_facts: False
  vars:
    routing:
      eigrp_as: 1
    interfaces:
      - name: GigabitEthernet0
        ipv4_address: 192.168.1.1/24
        eigrp4:
        ospfv2:
          area: 0
          cost: 1
          pri: 255
        eigrp6:
      - name: GigabitEthernet1

  tasks:
    - name: get the classfull networks for eigrp4
      block:
        - set_fact:
            ipv4a: "{{ interfaces | selectattr('eigrp4', 'defined') | map(attribute='ipv4_address') | ipaddr('address') | ipaddr('0.0.0.0/1') | map('regex_replace', '(\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b)', '\\1/8') | ipaddr('network') | list | unique }}"
            ipv4b: "{{ interfaces | selectattr('eigrp4', 'defined') | map(attribute='ipv4_address') | ipaddr('address') | ipaddr('128.0.0.0/2') | map('regex_replace', '(\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b)', '\\1/16') | ipaddr('network') | list | unique }}"
            ipv4c: "{{ interfaces | selectattr('eigrp4', 'defined') | map(attribute='ipv4_address') | ipaddr('address') | ipaddr('192.0.0.0/3') | map('regex_replace', '(\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b)', '\\1/24') | ipaddr('network') | list | unique }}"
        - set_fact:
            ipv4_classful_list: "{{ ipv4a + ipv4b + ipv4c }}"
    - debug:
        msg: "network {{ item.ipv4_address | ipaddr('network') }} {{ item.ipv4_address | ipaddr('hostmask') }} area {{ item.ospfv2.area }}"
      loop: "{{ interfaces | selectattr('eigrp4', 'defined') | list }}"
