---
- name: enable ospfv3 rid
  ios_config:
    defaults: yes
    parents: ipv6 router ospf {{ routing.ospf_pid | default(1) }}
    lines:
      - router-id {{ routing.rid }}
  when:
    - routing.rid is defined
    - interfaces | selectattr('ospfv3', 'defined') | list
- name: enable ospfv3 passive-interface
  ios_config:
    defaults: yes
    parents: ipv6 router ospf {{ routing.ospf_pid | default(1) }}
    lines:
      - passive-interface {{ item }}
  loop: "{{ routing.passive }}"
  when:
    - item is defined
    - interfaces | selectattr('ospfv3', 'defined') | list
- name: enable ospfv3 on interfaces
  ios_config:
    defaults: yes
    parents: interface {{ item.id }}
    lines:
      - "ipv6 ospf {{ routing.ospf_pid | default(1) }} area {{ item.ospfv2.area }}"
  loop: "{{ interfaces | selectattr('ospfv3', 'defined') | list }}"
  when:
    - item.id is defined
    - item.ospfv2.area is defined
    - interfaces | selectattr('ospfv3', 'defined') | list
