---
- name: enable eigrp4 rid
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.eigrp_as }}
    lines:
      - eigrp router-id {{ routing.rid }}
  when:
    - routing.eigrp_as is defined
    - routing.rid is defined
    - interfaces | selectattr('eigrp4', 'defined') | list
- name: enable eigrp4 passive-interface
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.eigrp_as }}
    lines:
      - passive-interface {{ item.name }}
  loop: "{{ interfaces | selectattr('passive', 'defined') | list }}"
  when:
    - routing.eigrp_as is defined
    - item.name is defined
- name: enable eigrp4 interfaces
  ios_config:
    defaults: no
    parents: router eigrp {{ routing.eigrp_as }}
    lines:
      - "network {{ item.ipv4_address | ipaddr('address') }} 0.0.0.0"
  loop: "{{ interfaces | selectattr('eigrp4', 'defined') | list }}"
  when:
    - routing.eigrp_as is defined
    - item.ipv4_address is defined
