---
- import_tasks: write_memory.yml
  when: ansible_network_os == 'ios'
  tags:
    - write
    - save
- import_tasks: get_config.yml
  when: ansible_network_os == 'ios'
  tags:
    - write
    - get
