- name: create vlans
  ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.id }}"
        state: active
        shutdown: disabled
  loop: "{{ vlans }}"
  when: item.name is defined
  when: item.id is defined
