---
- name: remove ip parameters to a trunk physical interface
#  ios_l3_interfaces:
#    config:
#      - name: "{{ item.id }}"
#    state: deleted
  ios_config:
    defaults: yes
    parents: interface {{ item.id }}
    lines:
      - no ip address
      - no ipv6 enable
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.trunk.vlans is undefined
    - item.trunk.native is undefined
- name: configure tagged vlans on subinterfaces
  ios_config:
    defaults: no
    parents: interface {{ item.id }}
    lines:
      - encapsulation dot1Q {{ item.trunk.vlans | default('1') }}
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.trunk.vlans is defined
- name: configure native untagged vlan on a subinterface
  ios_config:
    defaults: no
    parents: interface {{ item.id }}
    lines:
      - encapsulation dot1Q {{ item.trunk.native | default('1') }} native
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.trunk.native is defined
