---
- name: disable stub switchports
  ios_interfaces:
    config:
      - name: "{{ item.id }}"
        enabled: False
  loop: "{{ interfaces }}"
  when: item.stub is defined
- name: create stub vlan
  ios_vlans:
    config:
      - name: "{{ stubvlan.name }}"
        vlan_id: "{{ stubvlan.id }}"
        state: active
        shutdown: disabled
  when:
    - stubvlan is defined
- name: configure stub access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.id }}
    lines:
      - switchport mode access
      - switchport access vlan {{ stubvlan.id }}
  loop: "{{ interfaces }}"
  when:
    - stubvlan is defined
    - item.stub
- name: stp protection on stub access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.id }}
    lines:
      - spanning-tree portfast edge
      - spanning-tree bpduguard enable
  loop: "{{ interface }}"
  when:
    - stubvlan is defined
    - item.stub
