---
- name: configure access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.name }}
    lines:
      - switchport mode access
      - switchport access vlan {{ item.access.vlan | default('1') }}
  loop: "{{ interfaces | selectattr('access', 'defined') | list }}"
  when:
    - item.access is defined
- name: stp protection on access ports
  ios_config:
    defaults: yes
    parents: interface {{ item.name }}
    lines:
      - spanning-tree portfast edge
      - spanning-tree bpduguard enable
  loop: "{{ interfaces | selectattr('access', 'defined') | list }}"
  when:
    - item.access is defined
