---
- name: remove ip parameters to a trunk physical interface
  ios_l3_interfaces:
    config:
      - name: "{{ item.name }}"
    state: deleted
  loop: "{{ interfaces | selectattr('trunk', 'defined') | selectattr('trunk.vlan', 'undefined') | selectattr('trunk.native', 'undefined') | list }}"
- name: configure tagged vlans on subinterfaces
  ios_config:
    defaults: no
    parents: interface {{ item.name }}
    lines:
      - encapsulation dot1Q {{ item.trunk.vlan | default('1') }}
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.trunk.vlan is defined
- name: configure native untagged vlan on a subinterface
  ios_config:
    defaults: no
    parents: interface {{ item.name }}
    lines:
      - encapsulation dot1Q {{ item.trunk.native | default('1') }} native
  loop: "{{ interfaces | selectattr('trunk', 'defined') | list }}"
  when:
    - item.trunk.native is defined
