---
galaxy_info:
  author: goffinet
  description: configure RIPv2
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
    - ipv4
    - routing
    - rip
dependencies:
  - role: interface
  - role: ipv4
  - role: ipv4-routing
#  - role: disable-dynamic-ipv4-routing
