---
- name: enable eigrp ipv6 rid
  ios_config:
    defaults: yes
    parents: ipv6 router eigrp {{ routing.eigrp_as }}
    lines:
      - eigrp router-id {{ routing.rid }}
  when:
    - routing.eigrp_as is defined
    - routing.rid is defined
- name: enable eigrp ipv6 passive-interface
  ios_config:
    defaults: yes
    parents: ipv6 router eigrp {{ routing.eigrp_as }}
    lines:
      - passive-interface {{ item.name }}
  loop: "{{ interfaces | selectattr('passive', 'defined') | list }}"
  when:
    - routing.eigrp_as is defined
    - item.name is defined
- name: enable eigrp ipv6 on interfaces
  ios_config:
    defaults: yes
    parents: interface {{ item.name }}
    lines:
      - ipv6 eigrp {{ routing.eigrp_as }}
  loop: "{{ interfaces | selectattr('eigrp6', 'defined') | list }}"
  when:
    - item.name is defined
    - routing.eigrp_as is defined
    - interfaces | selectattr('eigrp6', 'defined') | list
