---
- name: enable nat outside interface
  ios_interfaces:
    config:
      - name: "{{ nat.outside }}"
        enabled: True
        description: TODO
- name: configure ipv4 adresses nat ouside interface
  ios_config:
    parents: interface {{ nat.outside }}
    lines:
      - ip address dhcp
      - ip nat outside
- name: configure ip nat inside interfaces
  ios_config:
    parents: interface {{ item }}
    lines:
      - ip nat inside
  loop: "{{ nat.inside }}"
- name: configure source nat acl
  ios_config:
    parents: ip access-list standard {{ nat.name }}
    lines:
      - permit {{ item }}
  loop: "{{ nat.sources }}"
- name: configure the nat rule
  ios_config:
    lines:
      - ip nat inside source list {{ nat.name }} interface {{ nat.outside }} overload
