---
galaxy_info:
  author: goffinet
  description: configure spanning-tree
  license: CC-BY-4.0
  min_ansible_version: 2.9
  galaxy_tags:
    - cisco
    - iosv
    - ccna
    - spanningtree
  platforms:
    - name: vios_l2-ADVENTERPRISEK9-M
      versions:
        - 15.2(20170321:233949)
dependencies:
  - role: interface
  - role: vlans
