---
- name: enable ipv4 dhcp server
  ios_config:
    defaults: yes
    parents: ip dhcp pool {{ item.id }}
    lines:
      - network {{ item.network }} {{ item.netmask }}
      - default-router {{ item.router }}
      - dns-server {{ item.dns }}
  loop: "{{ dhcp.dhcp_pool }}"
- name: exclude range from pool
  ios_config:
    defaults: yes
    lines:
      - ip dhcp excluded-address {{ item.start }} {{ item.end }}
  loop: "{{ dhcp.dhcp_excluded }}"
  when: dhcp.dhcp_excluded is defined
