---
- import_tasks: remove_banners.yml
  when:
    - ansible_network_os == 'ios'
    - banners.enabled is false
  tags:
    - banners
    - common
- import_tasks: configure_system.yml
  when: ansible_network_os == 'ios'
  tags:
    - common
