---
- name: configure fhrp - ipv4 address
  ios_config:
    parents: interface {{ item.id }}
    lines: "{{ item.mode }} {{ item.group }} ip {{ item.address }}"
  loop: "{{ fhrp }}"
  when: item.protocol == 'ipv4'
- name: configure fhrp - ipv6 address
  ios_config:
    parents: interface {{ item.id }}
    lines:
      - "{{ item.mode }} version 2"
      - "{{ item.mode }} {{ item.group }} ipv6 {{ item.address }}"
  loop: "{{ fhrp }}"
  when: item.protocol == 'ipv6'
- name: configure fhrp - priority
  ios_config:
    parents: interface {{ item.id }}
    lines: "{{ item.mode }} {{ item.group }} priority {{ item.priority }}"
  loop: "{{ fhrp }}"
  when: item.priority is defined
- name: configure fhrp - preemption
  ios_config:
    parents: interface {{ item.id }}
    lines: "{{ item.mode }} {{ item.group }} preempt"
  loop: "{{ fhrp }}"
  when: item.preempt == 'True'
