---
- name: enable ospfv2 rid
  ios_config:
    defaults: yes
    parents: router ospf {{ routing.ospf_pid | default(1) }}
    lines:
      - router-id {{ routing.rid }}
  when:
    - routing.rid is defined
    - interfaces | selectattr('ospfv2', 'defined') | list
- name: enable ospfv2 passive-interface
  ios_config:
    defaults: yes
    parents: router ospf {{ routing.ospf_pid | default(1) }}
    lines:
      - passive-interface {{ item }}
  loop: "{{ interfaces | selectattr('passive', 'defined') | list }}"
  when:
    - item is defined
- name: enable ospfv2 interfaces
  ios_config:
    defaults: yes
    parents: router ospf {{ routing.ospf_pid | default(1) }}
    lines:
      - "network {{ item.ipv4_address | ipaddr('network') }} {{ item.ipv4_address | ipaddr('hostmask') }} area {{ item.ospfv2.area }}"
  loop: "{{ interfaces | selectattr('ospfv2', 'defined') | list }}"
  when:
    - item.ipv4_address is defined
    - item.ospfv2.area is defined
