---
- import_tasks: enable_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
    - routing.ospfv2 is defined
  tags:
    - ospfv2
    - ipv4_dynamic_routing
- import_tasks: static_to_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
    - nat is defined
    - routing.ospfv2 is defined
  tags:
    - ospfv2
    - static_to_ospfv2
    - ipv4_dynamic_routing
