---
- name: ENABLE EIGRP IPv4
  hosts: core
  gather_facts: false
  tasks:
    - name: disable eigrp ipv4
      ios_config:
        lines: no router eigrp {{ item.as }}
      with_items: "{{ ipv4routing }}"
      register: print_output
    - debug: var=print_output

    - name: enable ospfv2
      ios_config:
        parents: router ospf {{ item[1].as }}
        lines:
          - router-id {{ item[1].rid }}
          - network {{ item[0].ipv4 }} 0.0.0.0
          - passive-interface {{ item[1].passive }}
      with_nested:
          - "{{ eigrp4 }}"
          - "{{ ipv4routing }}"
      register: print_output
    - debug: var=print_output
