---
- name: RESTORE CONFIGURATION
  hosts: core
  gather_facts: no
  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp ./config/{{inventory_hostname}}.cfg {{inventory_hostname}}:/{{inventory_hostname}}.cfg

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.cfg force
