---
- hosts: R1
  gather_facts: False
  tasks:
    - debug:
        msg: |
            "router ospf {{ item.0.pid }}
            "
      loop: "{{ routing | subelements('ipv4.ospfv2', skip_missing=True) }}"
